// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package strupro

import (
	flatbuffers "mxs/scenes/proto/flat/flatbuffers"
)

type TestMessage struct {
	_tab flatbuffers.Table
}

func GetRootAsTestMessage(buf []byte, offset flatbuffers.UOffsetT) *TestMessage {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TestMessage{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsTestMessage(buf []byte, offset flatbuffers.UOffsetT) *TestMessage {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TestMessage{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *TestMessage) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TestMessage) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TestMessage) Teststr() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func TestMessageStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TestMessageAddTeststr(builder *flatbuffers.Builder, teststr flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(teststr), 0)
}
func TestMessageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
