// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package strupro

import (
	flatbuffers "mxs/mmo/proto/flat/flatbuffers"
)

/// TalkMessage 聊天信息
type TalkMessage struct {
	_tab flatbuffers.Table
}

func GetRootAsTalkMessage(buf []byte, offset flatbuffers.UOffsetT) *TalkMessage {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TalkMessage{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsTalkMessage(buf []byte, offset flatbuffers.UOffsetT) *TalkMessage {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TalkMessage{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *TalkMessage) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TalkMessage) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TalkMessage) Eid() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TalkMessage) MutateEid(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *TalkMessage) Mid() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 1
}

func (rcv *TalkMessage) MutateMid(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *TalkMessage) Pos(obj *Position) *Position {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(Position)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *TalkMessage) S() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func TalkMessageStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func TalkMessageAddEid(builder *flatbuffers.Builder, eid int32) {
	builder.PrependInt32Slot(0, eid, 0)
}
func TalkMessageAddMid(builder *flatbuffers.Builder, mid int32) {
	builder.PrependInt32Slot(1, mid, 1)
}
func TalkMessageAddPos(builder *flatbuffers.Builder, pos flatbuffers.UOffsetT) {
	builder.PrependStructSlot(2, flatbuffers.UOffsetT(pos), 0)
}
func TalkMessageAddS(builder *flatbuffers.Builder, s flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(s), 0)
}
func TalkMessageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
